alias: Auto Mine
description: ""
trigger:
  - platform: time_pattern
    minutes: /15
condition: []
action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.sunsynk_18166_soc
            above: sensor.sunsunk_soc_cap
          - condition: state
            entity_id: sensor.nicehash_devicesstatuses
            state: INACTIVE
        sequence:
          - service: nh_nicehash.setrigstatus
            data:
              rigId: 0-cRyxRi9UzVWL6BGc3u0t2g
              action: START
      - conditions:
          - condition: numeric_state
            entity_id: sensor.sunsynk_18166_gridormeterpower
            above: 500
          - condition: state
            entity_id: sensor.nicehash_devicesstatuses
            state: MINING
        sequence:
          - service: nh_nicehash.setrigstatus
            data:
              rigId: 0-cRyxRi9UzVWL6BGc3u0t2g
              action: STOP
      - conditions:
          - condition: time
            after: "18:00:00"
          - condition: state
            entity_id: sensor.nicehash_devicesstatuses
            state: MINING
        sequence:
          - service: nh_nicehash.setrigstatus
            data:
              rigId: 0-cRyxRi9UzVWL6BGc3u0t2g
              action: STOP
mode: restart
